# Generated by Django 5.0.6 on 2024-06-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_book_category_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookisbn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='lms.book'),
        ),
    ]
